### ISSUE TITLE
Same menu in Bottom in action bar

### ISSUE THREAD

**Issue by rajam1215** [ibrahimsn98/SmoothBottomBar#39]
Hello @ibrahimsn98 @rezaepsilon0 @mayokunthefirst @brookmg @tobiasschuerg 

Please look in to this issue, **Bottom and action bar menus are same**, if user want to show other menu option in toolbar **with icon**, then how they will show, because **menu already occupied with bottom navigation**. without this solution **_library not useful for live projects or apps_**, please solve that.

Thanks

**Comment by brookmg** [comment]
What do you mean `menu already occupied with bottom navigation`? If you are talking about the menu resource files then you need to create two different resource files for each view.

**Comment by rajam1215** [comment]
@brookmg Ok thanks for reply, but if user **don't want to show menu 3 dots on toolbar**, then what to do, **_because for bottom navigation onCreateOptionsMenu is necessary may be_**. so user have any other choice ?

Or what to do for text largeness, **_all text not show when text is large_**.

**Comment by rajam1215** [comment]
> What do you mean `menu already occupied with bottom navigation`? If you are talking about the menu resource files then you need to create two different resource files for each view.

@brookmg Ok thanks for reply, but if user **don't want to show menu 3 dots on toolbar**, then what to do, **_because for bottom navigation onCreateOptionsMenu is necessary may be_**. so user have any other choice ?

Or what to do for text largeness, **_all text not show when text is large on bottom navigation_**.

**Comment by brookmg** [comment]
You actually asked two different questions ... 
1. Well, it seems like the library has changed a bit since my last contribution. The library has support for navigation components now and that's why it needs to utilize the method to bind menu resource like that. I don't work with navigation component so this is not my expertise. @mayokunthefirst might have a better answer.
2. You should look at #37 as it's an already existing issue.

**Comment by mayokunthefirst** [comment]
Hello @rajam1215 , if you don't want to show the menu dots on the toolbar, all you have to do is return false in `onCreateOptionsMenu`. i.e:
````kotlin
  override fun onCreateOptionsMenu(menu: Menu?): Boolean {
        menuInflater.inflate(R.menu.menu_bottom,menu)
        bottomBar.setupWithNavController(menu!!,navController)
        return false
    }
````
We would also find a better way to ensure that you don't have to override the `onCreateOptionsMenu` so that the library can suit all use cases. Finally as @brookmg said, about your request to disable text shortening, look at issue #37 .

**Comment by rajam1215** [comment]
Hello @mayokunthefirst i understand that.

you will enhance its functionality in future so user don't need to override, but please found the way of text shortening solution, so user can use this easlily without any problem.
